steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/maybank-anthos-poc/nodeapp3:$COMMIT_SHA'
      - '.'

  # Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/maybank-anthos-poc/nodeapp3:$COMMIT_SHA'

  # Set Cloud Run for Anthos
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'config'
      - 'set'
      - 'run/platform'
      - 'gke'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'config'
      - 'set'
      - 'run/cluster'
      - 'cloud-run-anthos-cluster'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'config'
      - 'set'
      - 'run/cluster_location'
      - 'asia-southeast1-a'
      
  # Update Cloud Run service
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'services'
      - 'update'
      - 'nodeapp3'
      - '--image'
      - 'gcr.io/maybank-anthos-poc/nodeapp3:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast1'
      
